### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by U10S1L** [U10S1L/bb-code-generator#3]
- [x] Convert to absolute imports
- [x] Investigate & Implement some solution for organizing imports
- [x] Adjust File Structure and move components around as necessary

**Comment by U10S1L** [comment]
Merged into Develop.
